server:
  port: 8088



spring:
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    datasource:
        name: sephiroth_base
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat,wall,log4j2
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://39.106.49.196:3306/sephiroth_base?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
          username: root
          password: uAiqwVwjJ8-i
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
          #关闭session统计功能
          use-local-session-state: false
          # 配置日志输出
          filter:
            slf4j:
              enabled: true
              statement-create-after-log-enabled: false
              statement-close-after-log-enabled: false
              result-set-open-after-log-enabled: false
              result-set-close-after-log-enabled: false
## 注释掉
#          # Druid StatViewServlet配置
#          stat-view-servlet:
#            enabled: true
#            url-pattern: /druid/*
#            reset-enable: true
#            login-username: admin
#            login-password: admin



#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: wzc.buyer.DAO
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
#  type-aliases-package: com.winterchen.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

#日志输出文件
logging:
  config: classpath:log4j2.yml

